In [1]:
import pandas as pd
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first =True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='str')

In [4]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent = dataset[['charges']]
independent
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [5]:
#  split the train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.3,random_state=0)

In [ ]:
# multiple linear regression
# from sklearn.linear_model import LinearRegression
# regressor = LinearRegression()
# regressor.fit(x_train,y_train)
# regressor

In [ ]:
# SVM regression
# standarised method
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.transform(x_test)
# x_train
# from sklearn.svm import SVR
# regressor = SVR(kernel = 'sigmoid',C=1000)
# regressor.fit(x_train,y_train)

In [ ]:
# Decision Tree regression
# standarised method
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.transform(x_test)
# x_train

# from sklearn.tree import DecisionTreeRegressor
# regressor = DecisionTreeRegressor(criterion='squared_error')
# regressor.fit(x_train,y_train)

In [12]:
# Random Forest regression
# standarised method
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 50,random_state=42,criterion='poisson')
regressor.fit(x_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(criterion='poisson', n_estimators=50, random_state=42)

In [ ]:
# import matplotlib.pyplot as plt
# from sklearn import tree
# tree.plot_tree(regressor)
# plt.show()

In [13]:
# Y_Predict
y_pred = regressor.predict(x_test)
y_pred

array([11408.9157224,  9815.0720248, 44909.4009622, 13073.282168 ,
        9600.2299082, 12349.8140488,  2178.453263 , 11413.1091814,
        7033.979202 ,  5211.234069 ,  7990.596602 , 20676.551065 ,
       10798.9067162,  5501.8503054, 24725.3667884, 13411.8625764,
       13478.6340388,  4205.0323218,  6546.6249196, 33902.1803426,
       23788.005128 , 15302.9616768, 10061.4741166, 28047.0268578,
        4050.673681 ,  5076.9112636,  3967.8096402,  8086.9618006,
        3697.948274 , 10357.045074 ,  7794.6594916, 48362.422062 ,
       13989.806553 , 15097.5071104, 16291.7484168,  3838.616792 ,
        8677.924418 , 37862.5092378, 39643.701531 ,  4134.611431 ,
        8515.9889858,  3411.33217  , 20148.478302 , 47922.801848 ,
       38284.1168902,  4788.5925124, 13417.8899434,  6527.302194 ,
        4904.226677 , 13297.3176692,  3680.554082 ,  4318.1370892,
       26630.1263684, 48048.453679 , 11809.340687 ,  6892.3946438,
        3483.2411172, 10429.1003904,  9896.4290094, 14468.4596892,
        1650.533309 , 46782.323252 , 16765.3752392, 18299.6192598,
       12300.9502036,  9846.01877  , 33828.1258036, 42095.0392852,
        3092.680425 , 12895.4225804, 19655.2132164, 13063.6592242,
       16960.352641 , 13886.632734 , 12842.563588 , 17157.3217878,
        8646.6179842, 14872.71608  , 19593.66312  , 46891.0474364,
       11539.230229 , 48445.4943888,  5450.707223 , 10984.5800528,
       40890.7510872, 19233.755209 ,  3344.3516024,  3709.3407508,
       13920.4004226, 40281.9159434,  5682.237539 , 14285.7443848,
        2849.069082 , 10275.2857434,  9112.9347422,  4197.68756  ,
       43048.340978 , 54982.1503132,  5193.2193384, 10991.702029 ,
        4150.4988094,  7336.0677762,  8274.8995214, 42445.4160862,
       28668.9435   ,  3967.3957872, 11284.092542 ,  5343.6841526,
       11591.750097 , 45349.753272 , 12169.165585 ,  6515.4344214,
       10277.1202922, 34316.5118522, 47971.3760492,  7036.068943 ,
        2052.879119 , 10479.2119974, 19049.5870136,  9733.6948708,
       42184.1096644, 13721.0043866, 14357.866759 ,  7817.4297838,
       10933.9990536,  5104.358856 , 26508.92913  , 26257.7308938,
       48383.718731 ,  1634.053302 , 14950.7380526,  2960.9590622,
        5931.206691 ,  8926.824468 , 42940.7649024, 38376.8524424,
       24928.756552 , 16582.8000566, 24484.913831 ,  7439.0921468,
        2037.090585 , 12030.9140752, 11246.1095122, 11032.030868 ,
        7224.7762458, 14178.158805 , 19810.6882176, 13388.157313 ,
        1583.002892 , 12935.8733896,  6179.580886 , 39920.473153 ,
        9838.3531028,  9613.1785682,  2896.281112 ,  6754.599989 ,
        4349.0163574,  6881.1102498, 13411.8625764,  9893.9098234,
        7740.0315336, 13441.070075 , 13928.310801 ,  9336.167822 ,
        4046.7363012,  8116.160066 , 17621.7196604,  6768.2605178,
        4613.2914188,  2116.976827 ,  6776.3509154,  7317.714472 ,
       11841.3084228,  2270.627159 , 11814.6186992,  8700.3898426,
        4731.1672202,  7258.915053 , 26623.344552 ,  2059.730814 ,
       18452.4489324,  7577.921114 , 11295.235747 ,  7865.406516 ,
       10320.1896714, 27987.1712754,  4014.9451658,  2803.1578764,
       14131.000653 , 11979.8414506, 41579.388468 ,  7637.5234496,
        5452.133096 , 25251.6848346,  2574.227054 ,  2774.7592144,
        7941.338373 ,  6006.784424 ,  8783.5155008,  5174.8549798,
       11973.1706216, 46084.797882 , 18670.2670078, 19003.933982 ,
       10367.6311204, 44531.4806676,  4776.055041 ,  9843.2763736,
        6778.4287984,  1697.752138 ,  8762.599017 , 13604.607434 ,
        7154.5841602,  5170.8740548,  7016.9337324, 10170.4408426,
        7253.24233  ,  6989.0778866, 14010.305064 ,  6840.547695 ,
       14851.8676816,  7853.519429 , 11677.1652324,  5648.1246388,
       12858.8059912, 14299.884028 , 20844.2443526, 12036.932967 ,
        7251.5956356,  2806.570659 , 10667.0216228,  8013.653881 ,
       13872.690876 ,  4156.9773036,  5261.771586 ,  7281.7034114,
       13363.248207 , 34613.2498476,  5813.098782 , 12767.2975534,
        6615.8547778, 37408.9671612,  8546.5968756,  7321.0459814,
       12171.0998884, 10198.534175 ,  3547.4290602,  9346.0741168,
        2646.5815328,  6442.168747 , 19660.536399 , 46176.471678 ,
        6092.3278954,  2967.882839 ,  4652.1600916,  1516.28239  ,
        7726.108613 ,  2584.350691 ,  6642.2139874,  9112.051994 ,
        8686.09479  , 25768.054113 , 45667.34534  , 16775.8173042,
        7056.4332724, 11146.133521 , 43886.5408784,  9697.4709818,
       39910.1303668,  1626.315898 , 39140.6015302,  5010.1795084,
       13233.3464498,  6803.9797734, 40313.4056854,  7021.211446 ,
        9840.998937 , 10368.5980606,  3711.09871  , 16473.2090794,
       12220.9291742, 10362.5089892, 12946.2606634, 13272.882112 ,
        5975.608535 ,  4808.0273736, 10035.0611742, 22982.3008572,
        3596.574701 ,  2061.194051 ,  2524.549481 , 47064.5275914,
       12755.7832464,  4678.6090728, 16434.4164234, 14774.700594 ,
       34814.2092296,  6777.390641 ,  5103.731286 ,  8852.256336 ,
        2920.1518594,  4247.0327454, 20845.385738 , 16608.395342 ,
       13807.3084812,  2807.144937 ,  3470.8448352, 11346.7996664,
        9945.7603076, 15216.4418982, 20026.466397 , 10901.9041708,
       17003.368102 ,  2148.777886 , 12147.7259512,  9360.68456  ,
       17381.3541184,  2291.433071 ,  7663.1940768, 46608.6687072,
        3654.3708798,  6968.6792086,  1773.511717 , 14559.3869534,
        5901.1298946, 11984.610313 , 46298.3830974, 18065.402917 ,
        8961.915794 , 45719.1184696, 17367.4119016, 10384.2782024,
        9975.6725032,  4846.944532 , 28703.355397 ,  4855.3383754,
       14649.4216452,  2276.877984 , 16580.619048 ,  3391.7982602,
       24575.558372 , 10298.6664464,  7451.3319618, 40827.3200766,
        5582.6568378,  5266.064339 , 29378.9235894,  2627.4960778,
       11023.1889644,  3763.0765838, 11219.97088  ,  4139.49817  ,
        7574.4306114,  6258.311508 , 45065.046983 ,  9229.3536938,
       44539.0369852, 39388.857886 ,  5832.091825 , 11804.5529198,
        1724.921189 ,  4456.514294 ,  3302.2562328,  9192.128791 ,
       45908.2179544, 11379.366406 ,  1867.171278 , 13787.5969176,
        2133.143396 , 12192.0764298,  7370.731912 ,  2715.516568 ,
        3277.62026  , 37469.7593636,  6737.903758 ,  1855.9779   ,
       40582.6403974, 13348.6320688, 43770.1089716, 11655.696432 ,
        6498.9582992,  3814.3722294,  2189.859017 , 17326.8534948,
        5006.301248 ,  1922.686376 , 11660.5965718,  7212.81047  ,
        6011.380947 ,  7972.12883  ,  8332.599313 , 43723.0308922,
        4404.3639432, 13711.5384514,  7460.974146 , 11296.129236 ,
       10988.732057 ,  5758.4476646, 17052.832374 , 14782.432547 ,
       21190.7130798, 19453.7020454])

In [14]:
# r2score matrics
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

0.8593601155052777

In [15]:
import pickle
filename = 'random_regression.sav'
pickle.dump(regressor,open(filename,'wb'))
loaded_model = pickle.load(open('random_regression.sav','rb'))

In [20]:
user_age = float(input("Enter Age: "))
user_bmi = float(input("Enter BMI: "))
user_children = float(input("Enter Number of Children: "))
user_sex = float(
    input("Enter Sex (1 for Male, 0 for Female): ")
)  # Male = 1, Female = 0
user_smoker = float(
    input("Enter Smoker (1 for Yes, 0 for No): ")
)  # Yes = 1, No = 0
result = loaded_model.predict([[user_age,user_sex,user_bmi,user_children,user_smoker]])
result
# input_data = pd.DataFrame(
#     [[user_age, user_bmi, user_children, user_sex, user_smoker]],
#     columns=['age', 'bmi', 'children', 'sex_male', 'smoker_yes'],
# )

# 4. Predict செய்து முடிவைக் காட்டுதல்
# prediction = loaded_model.predict(input_data)
# prediction

Enter Age:  60
Enter BMI:  30.78
Enter Number of Children:  5
Enter Sex (1 for Male, 0 for Female):  0
Enter Smoker (1 for Yes, 0 for No):  0

array([21622.7456794])