In [1]:
import pandas as pd
from pca import (PCAUnSup, Linear, svm_linear, 
    svm_NL, Decision, random, selectk_regression)
import warnings;
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_csv('Wine.csv')
X = dataset.drop('Customer_Segment',axis=1)
y = dataset['Customer_Segment']
X

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [3]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Customer_Segment, Length: 178, dtype: int64

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
# 1. Get PCA explained variance values
getPCA = PCAUnSup(X_train, X_test, 8)

# 2. Convert to DataFrame and assign column name
df_pca = pd.DataFrame(getPCA, columns=['Explained Variance Ratio'])

# Display result
df_pca

   Explained Variance Ratio
0                  0.368841
1                  0.193184
2                  0.107529
3                  0.074220
4                  0.062459
5                  0.049090
6                  0.041173
7                  0.024960

In [ ]:
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

r2_lin=Linear(X_train,y_train,X_test,y_test)
acclin.append(r2_lin)
print(acclin)
r2_sl=svm_linear(X_train,y_train,X_test,y_test)    
accsvml.append(r2_sl)

r2_NL=svm_NL(X_train,y_train,X_test,y_test)
accsvmnl.append(r2_NL)

r2_d=Decision(X_train,y_train,X_test,y_test)
accdes.append(r2_d)

r2_r=random(X_train,y_train,X_test,y_test)
accrf.append(r2_r)
    
    
result = selectk_regression(acclin, accsvml, accsvmnl, accdes, accrf)
result

In [ ]:
# 5
result

In [ ]:
# 3
result