In [1]:
import pandas as pd
from selectk_Regression import (
    selectkbest, split_scalar, Linear, svm_linear, 
    svm_NL, Decision, random, selectk_regression
)
import warnings;
warnings.filterwarnings('ignore')

In [2]:
dataset1 = pd.read_csv("prep.csv")
df2 = pd.get_dummies(dataset1,dtype=int, drop_first=True)
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [3]:
indep_X = df2.drop('classification_yes', axis=1)
dep_Y = df2['classification_yes']

In [13]:
kbest, selected_cols = selectkbest(indep_X, dep_Y, 7)
X_train, X_test, y_train, y_test = split_scalar(kbest, dep_Y)

In [14]:
pd.DataFrame(kbest,columns=selected_cols)

      al         bgr          bu        sc       hrmo        pcv            wc
0    3.0  148.112676   57.482105  3.077356  12.518156  38.868902   8408.191126
1    2.0  148.112676   22.000000  0.700000  10.700000  34.000000  12300.000000
2    1.0   99.000000   23.000000  0.600000  12.000000  34.000000   8408.191126
3    1.0  148.112676   16.000000  0.700000   8.100000  38.868902   8408.191126
4    0.0  148.112676   25.000000  0.600000  11.800000  36.000000  12400.000000
..   ...         ...         ...       ...        ...        ...           ...
394  0.0  219.000000   36.000000  1.300000  12.500000  37.000000   9800.000000
395  0.0  220.000000   68.000000  2.800000   8.700000  27.000000   8408.191126
396  3.0  110.000000  115.000000  6.000000   9.100000  26.000000   9200.000000
397  0.0  207.000000   80.000000  6.800000   8.500000  38.868902   8408.191126
398  0.0  100.000000   49.000000  1.000000  16.300000  53.000000   8500.000000

[399 rows x 7 columns]

In [15]:
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

r2_lin=Linear(X_train,y_train,X_test,y_test)
acclin.append(r2_lin)
print(acclin)
r2_sl=svm_linear(X_train,y_train,X_test,y_test)    
accsvml.append(r2_sl)

r2_NL=svm_NL(X_train,y_train,X_test,y_test)
accsvmnl.append(r2_NL)

r2_d=Decision(X_train,y_train,X_test,y_test)
accdes.append(r2_d)

r2_r=random(X_train,y_train,X_test,y_test)
accrf.append(r2_r)
    
    
result = selectk_regression(acclin, accsvml, accsvmnl, accdes, accrf)
result

[0.6570348953434939]

             Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.657035  0.641906  0.893007  0.826389  0.916233

result